### PR TITLE
Add test config and allow it to be used via `process.env`

### PR DESCRIPTION
**Pull request by jackboberg**

### CODE REVIEW

**Comment by tzmanics** [comment]
:+1: once conflicts resolved

**Comment by harlanj** [comment]
@jackboberg is this PR still relevant?

**Comment by jackboberg** [comment]
Potentially, but it can not be safely merged right now, and I have better things to do that work on this 😄 .

**Comment by franvarney** [comment]
Do you think it's a good idea to update the config to the way we normally do it now?

**Comment by jackboberg** [comment]
Honestly, I have no interest in maintaining this code. It will be completely removed from our projects soon enough.

**Comment by franvarney** [comment]
Ok, I'm going to close

**Pull request closed without merging**
